version : '2'

services:
 tomcat:
  image: quentinv/cmdbuild:t6-2.2.0
  ports:
   - 8080:8080
  restart: always 
  networks:
   - cmdbuild-network

 pgsql:
  image: postgres:9.3
  restart: always
  environment:
   - POSTGRES_PASSWORD=YOUR_POSTGRES_PASSWORD
  networks:
   - cmdbuild-network
   
networks:
   cmdbuild-network:
     driver: bridge

