tomcat:
  image: quentinv/cmdbuild:t6-1.4.0.2
  ports:
   - 8080:8080
  restart: always 
  links:
   - pgsql:database
   

pgsql:
  image: postgres:9.3
  restart: always
  environment:
   - POSTGRES_PASSWORD=YOUR_POSTGRES_PASSWORD